---
features:
  - |
    Make simulator backends configurable. This allows setting persistant options
    such as simulation method and noise model for each simulator backend object.

    The :class:`~qiskit.providers.aer.QasmSimulator` and
    :class:`~qiskit.providers.aer.PulseSimulator` can also be configured from
    an IBMQ backend object using the
    `:meth:`~qiskit.providers.aer.QasmSimulator.from_backend` method.
    For the QasmSimulator this will configure the coupling map, basis gates,
    and basic device noise model based on the backend configuration and
    properties. For the PulseSimulator the system model and defaults will be
    configured automatically from the backend configuration, properties and
    defaults.
