name: Doc and tutorial tests
on:
  push:
    branches: [master, 'stable/*']
  pull_request:
    branches: [master, 'stable/*']
jobs:
  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-docs-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-docs-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install Deps
        run: |
          set -e
          pip install -U pip virtualenv wheel
          pip install -U tox
          sudo apt-get update
          sudo apt-get install -y build-essential libopenblas-dev
        shell: bash
      - name: Run Docs Build
        run: tox -edocs
      - uses: actions/upload-artifact@v2
        with:
          name: html_docs
          path: docs/_build/html
  tutorials:
    name: Tutorials
    runs-on: ubuntu-latest
    needs: [docs]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Pip cache
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-tutorials-${{ hashFiles('setup.py','requirements-dev.txt','constraints.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-tutorials-
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Setup tutorials job
        run: |
          set -e
          git clone https://github.com/Qiskit/qiskit-tutorials --depth=1
          python -m pip install --upgrade pip wheel
          pip install -U -r requirements-dev.txt -c constraints.txt
          pip install -c constraints.txt git+https://github.com/Qiskit/qiskit-terra
          pip install -c constraints.txt .
          pip install -U "qiskit-ibmq-provider" "z3-solver" "qiskit-ignis" "qiskit-aqua" "pyscf<1.7.4" "matplotlib<3.3.0" jupyter pylatexenc sphinx nbsphinx sphinx_rtd_theme cvxpy -c constraints.txt
          python setup.py build_ext --inplace
          sudo apt install -y graphviz pandoc libopenblas-dev
          pip check
        shell: bash
      - name: Run Tutorials
        run: |
          set -e
          cd qiskit-tutorials
          rm -rf tutorials/chemistry tutorials/circuits tutorials/circuits_advanced tutorials/finance tutorials/optimization tutorials/noise
          sphinx-build -b html . _build/html
      - uses: actions/upload-artifact@v2
        with:
          name: tutorials_html
          path: qiskit-tutorials/_build/html
