name: Standalone compile test
on:
  push:
    branches: [master, 'stable/*']
  pull_request:
    branches: [master, 'stable/*']
jobs:
  standalone:
    name: compile-standalone-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macOS-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install deps
        run: pip install "urllib3<1.26" conan
      - name: Install openblas
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev
        shell: bash
        if: runner.os == 'Linux'
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        if: runner.os == 'Windows'
      - name: Compile Standalone Windows
        run: |
          set -e
          mkdir out; cd out; cmake .. -DBUILD_TESTS=1
          cmake --build . --config Release
        shell: bash
        if: runner.os == 'Windows'
      - name: Compile Standalone
        run: |
          set -e
          mkdir out; cd out; cmake .. -DBUILD_TESTS=1
          make
        shell: bash
        if: runner.os != 'Windows'
      - name: Run Unit Tests
        run: |
          cd out/bin
          for test in test*
          do echo $test
            if ! ./$test
            then
              ERR=1
            fi
          done
          if [ ! -z "$ERR" ]
          then
            exit 1
          fi
        shell: bash
