name: Wheel Build Tests
on:
  push:
    branches: [master, 'stable/*']
  pull_request:
    branches: [master, 'stable/*']
jobs:
  wheel:
    name: compile-wheel-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["macOS-latest", "ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: python -m pip install -U cibuildwheel==1.5.5
      - name: Build Wheels
        env:
          CIBW_BEFORE_ALL_LINUX: "yum install -y openblas-devel"
          CIBW_BEFORE_BUILD: "pip install -U virtualenv pybind11"
          CIBW_SKIP: "cp27-* cp34-* cp35-* pp*"
          CIBW_MANYLINUX_X86_64_IMAGE: "manylinux2010"
          CIBW_MANYLINUX_I686_IMAGE: "manylinux2010"
          CIBW_TEST_COMMAND: "python3 {project}/tools/verify_wheels.py"
          CIBW_TEST_REQUIRES: "git+https://github.com/Qiskit/qiskit-terra.git"
        run: cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
